### PR TITLE
avoid deprecated GtkStock

### PR DESCRIPTION
**Pull request by sc0w**
The expected with this PR: the same icons like before

### CODE REVIEW

**Comment by lukefromdc** [comment]
Applet help issue reported at
https://github.com/mate-desktop/mate-power-manager/issues/243

**Comment by raveit65** [comment]
I can confirm the issue with the applets with master branch. Help doesn't open and yelp itself i crashing here and generates a abrt alarm in fedora.
Indeed, after help is called one time from m-p-m gui it opens fine from applets too.

**Comment by raveit65** [comment]
Hmm, we use 'help-about' and 'gtk-about'. Looks like 'gtk-about' displays the term info?

**Comment by sc0w** [comment]
@raveit65 

"help-about" and "gtk-about" shows the same icon

the deprecated function `gtk_image_menu_item_new_from_stock`:
https://developer.gnome.org/gtk3/stable/GtkImageMenuItem.html#gtk-image-menu-item-new-from-stock

the replacement is `gtk_menu_item_new_with_mnemonic `but we will loss icons

so, I keep the deprecated function, but it doesn't work with icon names, so, I use "gtk-about" and it works

for reference:
https://github.com/GNOME/gtk/blob/gtk-3-22/gtk/deprecated/gtkstock.h#L114

**Comment by sc0w** [comment]
I forgot to say: I think the translations aren't affected

**Comment by raveit65** [comment]
@sc0w 
My question was not about the icon.
It was about different text in menu entries.
In brightness or inhibit applet we use 'about' and in gpm na-tray icon we use 'info'.

**Comment by sc0w** [comment]
@raveit65 

I have tested with mate-calc git master, with same code like here (gtk_image_menu_item_new_from_stock "gtk-about")

and with [`env LANG=de_DE.UTF-8 mate-calc`] I see **Info** too, and with other languages I see other words

**Comment by raveit65** [comment]
Ok , than it is already in master and not related to PR.
Personal, i don't care if i see 'info' or 'about' there. The meaning is very similar in german.

**Pull request merged**
