### PR TITLE
Unable to change keyboard back light #108

### PR DESCRIPTION
**Pull request by mesouug**
Fixed issue for laptops with levels less then 10;

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Looks good to me. But I only have one laptop with a keyboard back light. It is on loan and being sent back this week. @infirit @monsta @raveit65 do you have hardware to test on?

**Comment by monsta** [comment]
raveit65 is @NiceandGently :smile:

Unfortunately, I don't have such hardware around...

**Comment by NiceandGently** [comment]
My notebook doesn't have keyboard backlight

**Comment by infirit** [comment]
Neither do I. If it does not break anything on @flexiondotorg's laptop then let's merge it..

**Pull request merged**
