### PR TITLE
Scale OSD size correctly on HiDPI displays

### PR DESCRIPTION
**Pull request by vkareh**
Related: https://github.com/mate-desktop/mate-settings-daemon/pull/212

### CODE REVIEW

**Comment by vkareh** [comment]
@lukefromdc - updated this too

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-settings-daemon/pull/212 now works fine, I'll build this one and try it on the netbook when I get home tonight from something I need to go out to now

**Comment by flexiondotorg** [comment]
Tested on my Dell XPS 15 in HiDPI and unscaled mode with and without a compositor. Works great.

**Comment by vkareh** [comment]
@lukefromdc - thanks for testing all my iterations! :)

I just checked and I can see the off-to-the-left issue if I go down in resolution low enough. It's not really present at higher resolutions, let alone at HiDPI resolutions, so I'm not sure we need to address that at the moment as anyone using tiny screens at HiDPI scales should expect to see weird stuff 😉

**Comment by vkareh** [comment]
@raveit65 - I've squashed the commits for both https://github.com/mate-desktop/mate-settings-daemon/pull/212 and https://github.com/mate-desktop/mate-power-manager/pull/246

**Pull request merged**
