### PR TITLE
minor language issue

### PR DESCRIPTION
**Pull request by rjmaris**
I'm sorry becaus of non-conformous contribution. Attached is a zipped patch file

[0001-Minor-translation-issues-wit-english-Rate-and-Histor.patch.zip](https://github.com/mate-desktop/mate-power-manager/files/1309479/0001-Minor-translation-issues-wit-english-Rate-and-Histor.patch.zip)

### CODE REVIEW

**Comment by raveit65** [comment]
We use transifex for translation.
https://www.transifex.com/
Create a account there ,become a member of your language group and fix the translation there, please.
Thanks.

@monsta 
Why i see code commits from you here ?  :-)

**Comment by rjmaris** [comment]
From the transifex website: "Source content and translations are automatically synced to a global content repository that’s accessible any time"

@ravati65: When this is the underlying mechanism, that will not work. It is not possible to have single word translations right all time in the associated context. Either this must be done manually or the phrase "Rate" must be replaced by e.g. "power drag", "power consumption". But not "Rate"!
Then, an automated translation process based on a "global content repository" would do a quite fair job.

**Comment by monsta** [comment]
@raveit65 this is an attempt to merge 1.18 branch into master, which we shouldn't do.

**Comment by rjmaris** [comment]
@monsta: whos attempt is it to merge a branch into master?

**Comment by monsta** [comment]
proof

**Comment by rjmaris** [comment]
OK, now I'm sure that you believe that I'm the one who did the attempt. This offending is not acceptable. I don't know how two commits with a July date got into my pull request. The only thing I did was creating a pull request, upload a ZIP-file and write a little explanation.

Or said another way round: what could have happened that these commits got part of the pull request?

**Pull request closed without merging**
