### PR TITLE
Scale OSD size correctly on HiDPI displays

### PR DESCRIPTION
**Pull request by vkareh**
Related: https://github.com/mate-desktop/mate-settings-daemon/pull/211

### CODE REVIEW

**Comment by lukefromdc** [comment]
Should this be held off on pending a fix for the non-composited case like
https://github.com/mate-desktop/mate-settings-daemon/pull/211 ?

**Comment by vkareh** [comment]
Yeah, sorry about that - let's hold off on this one as well (this one doesn't seem to be affected, but they are inter-related enough that I'd rather get them both in together)

**Comment by vkareh** [comment]
@lukefromdc, @flexiondotorg - okay, this should be ready for testing now (try it on both composited and non-composited wm, just to be sure)

**Comment by lukefromdc** [comment]
I can't get an OSD from this on the desktop, holding off on moving this to the netbook for testing pending any changes in https://github.com/mate-desktop/mate-settings-daemon/pull/211 for the problem of having to restart m-s-d (maybe m-p-m in this case?) to avoid corrupted rendering

**Comment by vkareh** [comment]
@lukefromdc - I've updated this. You might need to do the m-s-d one first for this one to work properly.

**Comment by vkareh** [comment]
Needs quite a bit of rewrite to support dynamic rescaling... closing for now

**Pull request closed without merging**
