### PR TITLE
brightness applet: properly hide popup on Esc/Enter/Space keys

### PR DESCRIPTION
**Pull request by monsta**
the new code was looked up in upstream brightness applet...

fixes https://github.com/mate-desktop/mate-power-manager/issues/203

### CODE REVIEW

**Comment by monsta** [comment]
I don't get that here with the same GTK+ in Debian Testing...

Seems like a build with disabled deprecated stuff in GTK+ (GtkStatusIcon is deprecated and the compiler can't find it because deprecated stuff is off).

**Comment by lukefromdc** [comment]
I can't see how that disable deprecated would get turned on when using the exact same build options I normally use for sucessful builds from master but that's exactly what it looks like

**Comment by monsta** [comment]
Weird... and I didn't make any changes in these files where the build error happens.

@raveit65: can you check it too please?

**Comment by raveit65** [comment]
Sometimes i got this error in the past also with other packages during distcheck.
Here i could simply avoid that with using a rhel7 VM with another libtool version to create the tarball.
And i ran only in this issue if i compiled by hand, not using a fedora or local build server to create a rpm.

**Comment by raveit65** [comment]
Damned, i got this error now i compiling by hand on f24 (gtk+-3.20)
```
In file included from gpm-manager.c:60:0:
gpm-tray-icon.h:59:1: error: unknown type name 'GtkStatusIcon'
 GtkStatusIcon *gpm_tray_icon_get_status_icon  (GpmTrayIcon *icon);
 ^~~~~~~~~~~~~
gpm-manager.c:97:2: error: unknown type name 'GtkStatusIcon'
  GtkStatusIcon  *status_icon;
  ^~~~~~~~~~~~~
gpm-manager.c: In function 'gpm_manager_notify':
gpm-manager.c:487:6: warning: implicit declaration of function 'gtk_status_icon_is_embedded' [-Wimplicit-function-declaration]
      gtk_status_icon_is_embedded (manager->priv->status_icon))
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
gpm-manager.c:488:59: warning: implicit declaration of function 'gtk_status_icon_get_icon_name' [-Wimplicit-function-declaration]
   notification = notify_notification_new (title, message, gtk_status_icon_get_icon_name(manager->priv->status_icon));
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gpm-manager.c:488:59: warning: passing argument 3 of 'notify_notification_new' makes pointer from integer without a cast [-Wint-conversion]
In file included from /usr/include/libnotify/notify.h:27:0,
                 from gpm-manager.c:44:
/usr/include/libnotify/notification.h:114:21: note: expected 'const char *' but argument is of type 'int'
 NotifyNotification *notify_notification_new                  (const char         *summary,
                     ^~~~~~~~~~~~~~~~~~~~~~~
```
but compiling with './autogen.sh && make' in a directory **without** the .git folder gives me no error ;-)
Now i recall that it was only a problem with using distcheck for creating a tarball, as we need the folder to generate the changelog from git.

**Comment by monsta** [comment]
Ok, I think I know what's going on... I always build .deb packages using Debian build files from our debian-packages repo, and there's ```--disable-strict``` switch in [debian/rules](https://github.com/mate-desktop/debian-packages/blob/master/mate-power-manager/debian/rules) there. But if you don't explicitly enable or disable this build option, then it gets auto-enabled if there's a .git folder present. See this block in configure.ac:

```
dnl ---------------------------------------------------------------------------
dnl - Use strict options (default enabled for devs, disabled in releases)
dnl ---------------------------------------------------------------------------
dnl if .git directory is present, considering we are working in the repository
if test -d ".git"; then
	default_strict=yes
else
	default_strict=no
fi
```
I think we better remove this part to avoid the same problem in the future. Disabling deprecated stuff just doesn't make sense for us. We still have a lot of deprecations in all our projects, and possibly will have some of them in the future (GtkStock, GtkStatusIcon, icons in menus and on buttons).

**Comment by raveit65** [comment]
Of course this needs to be removed, this makes no sense and And stole my time.

**Comment by monsta** [comment]
@lukefromdc: can you try it once more? I've added a commit which removes these "strict" options.

**Comment by lukefromdc** [comment]
Build failure is gone-and this fixes a nasty bug. Without this PR, using esc crashes the applet, with it, the popup is closed without issue by the esc key. This seems to be ready to go

**Pull request merged**
