### PR TITLE
engine: Use primary instead of composite when n<=1

### PR DESCRIPTION
**Pull request by smclt30p**
With the release of Linux 4.17, the kernel will support the setting
of battery charge thresholds on Lenovo ThinkPad laptops.

This means, that some of the batteries can be in a state of "Not
Charging", which is new to the ACPI battery driver.

When in such a state, GPM reports a wrong icon in the tray
(battery-missing-symbolic) because the state on the fake composite
device is not updated.

This patch returns the actual device if the number of batteries is
only 1 instead of the composite device. This fixes the icon in the
tray.

If the number of batteries is greater than 1, the fake composite
device is returned and everyhting resumes business as usual.

Signed-off-by: Ognjen Galic <smclt30p@gmail.com>

### CODE REVIEW

**Comment by lukefromdc** [comment]
Does anyone hear own a Lenovo Thinkpad?

**Comment by smclt30p** [comment]
I do, a X220. Works on my machine.

pic

```
Device: /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               LGC
  model:                45N1025
  serial:               15643
  power supply:         yes
  updated:              Ned 04 Mar 2018 00:09:21 (20 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               pending-charge
    warning-level:       none
    energy:              15,93 Wh
    energy-empty:        0 Wh
    energy-full:         17,82 Wh
    energy-full-design:  62,16 Wh
    energy-rate:         0 W
    voltage:             12,364 V
    percentage:          89%
    capacity:            28,668%
    technology:          lithium-ion
    icon-name:          'battery-full-charging-symbolic'
```

```
gala@thinkpad:~/src/gpm-test/mate-power-manager$ cat /sys/class/power_supply/BAT0/status 
Not charging
```

To test this, you need to wait for 4.17 or build the linux-next branch from kernel.org

**Comment by raveit65** [comment]
I can only test it with my MSI fx700, but i need to wait if kernel-4.17 is in fedora 27.

**Comment by smclt30p** [comment]
Scratch this pull request, there is a bug in UPower itself and this is beating around the bush. Discard this.

**Pull request closed without merging**
