### PR TITLE
Choosing interfaces under /sys/class/backlight, UPOWER_ENABLE_DEPRECATED defines.

### PR DESCRIPTION
**Pull request by roobre**
Now the user is able to define which interface under /sys/class/backlight will be used to manage the brightness.
Despite I'm investigating a "better" method using XRandr, I have no guarantees about if it can be done or not, so I post the pull request with this method.

`UPOWER_ENABLE_DEPRECATED` has also been added, to enable compilation on systems which use newer versions of upower.

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@stefano-k Please review this for inclusion in MATE 1.10

**Comment by monsta** [comment]
This PR has merge conflicts and needs to be rebased. That is, if it's still relevant. Almost two years have passed.

**Comment by flexiondotorg** [comment]
@roobre Please can you rebase this pull-request so we can merge it?

**Comment by roobre** [comment]
Hello,
Sorry, but I'm afraid I deleted my fork of the repo about a year ago, as I supposed this would be ignored :\

Feel free to close this request if you want.

Regards, Roberto.

**Comment by monsta** [comment]
@flexiondotorg: ok, then it can be closed.

**Pull request closed without merging**
