### PR TITLE
Port libunique to GtkApplication

### PR DESCRIPTION
**Pull request by mspaulding06**
Hi, I've made an attempt to port mate-power-manager from libunique to GtkApplication.

Tested on Ubuntu-MATE 16.04.1 with Gtk 3.18.9 and everything appears to be working correctly with the patch.

### CODE REVIEW

**Comment by monsta** [comment]
Please don't break GTK+2 build yet...

**Comment by raveit65** [comment]
GtkApplication is for gtk3.
Can you use GTK_CHECK_VERSION ?
Also  a git rebase is needed to include latest changes from master.

**Comment by mspaulding06** [comment]
Okay, I can make those changes.  So libunique support needs to stay in place for GTK+2?  Am I understanding correctly?

**Comment by monsta** [comment]
Yes, because GtkApplication is in GTK+3 only. You can check https://github.com/mate-desktop/mate-user-share/pull/40 as an example...

**Comment by monsta** [comment]
Thanks, I've tested it in GTK+2 build, it builds and works alright.

**Comment by monsta** [comment]
Ok, builds in GTK+3, but the affected applications (```mate-power-preferences``` and ```mate-power-statistics```) are not single-instance anymore... I guess you need to use ```g_application_run``` or something like that - see https://github.com/mate-desktop/mate-user-share/pull/40 once again.

**Comment by raveit65** [comment]
gtk3 build works fine here.

**Comment by raveit65** [comment]
btw. i found some links for comparing.
first to GApplication
https://git.gnome.org/browse/gnome-power-manager/commit/?id=10e86eb2f2d6b02ba92fe8ba449cf4553474dfb9
https://git.gnome.org/browse/gnome-power-manager/commit/?id=f0749b27476c40f254fe6d6d9610294420724ad5
than GtkApplication
https://git.gnome.org/browse/gnome-power-manager/commit/?id=b9f9334b5f118833391ae7daa57514c61f90e261

**Comment by mspaulding06** [comment]
Thanks for the links, that's helpful.  Based on these commits it looks like I should be using `gtk_application_run` and `gtk_application_quit` which I am not.  Maybe I should fix this?  Just wondering why all the example code on their libunique migration page would show using `g_application_run` if you're not supposed to use it.

**Comment by monsta** [comment]
I don't see ```gtk_application_run``` and ```gtk_application_quit``` in the [docs](https://developer.gnome.org/gtk3/stable/GtkApplication.html).

**Comment by monsta** [comment]
BTW, I'm not sure if we need to do some additional work on closing the window. Single instance app has only one main window, so there should be no need to get list of all windows and use ```gtk_widget_destroy``` on them. The code in https://github.com/mate-desktop/mate-user-share/pull/40 looks simpler than this. It seems to follow [this doc](https://developer.gnome.org/gtk3/stable/gtk-migrating-unique-GtkApplication.html).

**Comment by raveit65** [comment]
OK, those links are from 2.31.4.
Found another one from 2.91.2 where all was changed ;)
https://git.gnome.org/browse/gnome-power-manager/commit/?id=9bdb0db30dbe3fbd6dd30c3de1914552449ea681
At this time gpm-prefs was already moved to control-center.

**Comment by mspaulding06** [comment]
@monsta The document you're referring to doesn't show any quit handlers, so I can't learn how to do it from there.  I did notice there is a function `g_application_quit` that I could try using instead with the doc [here](https://developer.gnome.org/gio/stable/GApplication.html#g-application-quit).  And now that I'm looking again m-u-s is using `gtk_widget_destroy` directly on the window.  That's another good option.

**Comment by raveit65** [comment]
I just tested again on bare metal system and starting prefs or statistics from 2 terminals.
If the window is already open from 1 terminal, i see for a very short time (0.5 s) that the second window opens and closed.
Don't know if that is normal for GtkApplication, but i never saw this before with a app.

**Comment by mspaulding06** [comment]
That's strange behavior.  I wonder if it is because I call `gtk_window_present` from a signal callback instead of from main.  Maybe I'll try that and see if it makes any difference.

**Comment by mspaulding06** [comment]
Ok, this strange behavior is fixed now.  Just need to not call `gtk_widget_show` for the gtk3 version of the code.

**Comment by raveit65** [comment]
Great, that works now.
Executing a second instants from a terminal will only give the already opened window focus.
So, it works like it should.
@monsta 
I think we can merge it if you are fine with it.

**Comment by monsta** [comment]
I think the prefs app could make use of ```gtk_widget_destroy``` as well :smile:

**Comment by monsta** [comment]
Seems to work in GTK+3 build, but the stats app gives a warning on quit:

```
(mate-power-statistics:21706): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed
```

**Comment by mspaulding06** [comment]
All quit warnings should now be gone (either if you click the close box or if you click the close button).

**Comment by raveit65** [comment]
Confirmed, no close warnings any more, thank you.

**Comment by monsta** [comment]
Squashed and merged in https://github.com/mate-desktop/mate-power-manager/commit/69be34ae5e905b2db1f44f84259133d8914f675f, thanks!

**Pull request closed without merging**
