### PR TITLE
Fix spelling and grammar mistakes

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by rbuj** [comment]
suspension noun (STOP)
https://dictionary.cambridge.org/us/dictionary/english/suspension

**Comment by lukefromdc** [comment]
Not opposing this, just asking the other devs what they think.

**Comment by rbuj** [comment]
Suspend Failure section makes reference to suspend to disk (hibernation), as well as to suspend to RAM (suspend). I think that the section name must be changed to "Suspend/Hbernate Failure", because the warnings are:
<pre>
src/egg-console-kit.c:          egg_warning ("Couldn't suspend: %s", error_local->message);
src/egg-console-kit.c:          egg_warning ("Couldn't hibernate: %s", error_local->message);
</pre>
I couldn't find "Suspend Problem" in the current code:
<pre>
git grep "Suspend Problem" -- './*' ':*.{docbook,xml}' ':!*.po' ':!*.pot'
</pre>

**Comment by raveit65** [comment]
I don't think that you will see consolekit warnings on systemd box from modern fedora/ubuntu/debian.
As far i know only gentoo Mate maintainer prefer to use deprecated consolekit in their ebuilds.
Honestly , i don't understand those systemd-haters anymore ;)

**Comment by raveit65** [comment]
> suspension noun (STOP)
https://dictionary.cambridge.org/us/dictionary/english/suspension

I speak only pidgin english, so i can't say what is better.
But i would prefer a common usage of a word if it sounds better for native english speakers.

**Comment by rbuj** [comment]
$ cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)
$ dbus-send --system --print-reply \
--dest=org.freedesktop.login1 /org/freedesktop/login1 \
"org.freedesktop.login1.Manager.Suspend" boolean:true
Error org.freedesktop.DBus.Error.AccessDenied: Permission denied

**Comment by raveit65** [comment]
This working here with f28
```
[rave@satellite ~]$ dbus-send --system --print-reply \
> --dest=org.freedesktop.login1 /org/freedesktop/login1 \
> "org.freedesktop.login1.Manager.Suspend" boolean:true
method return time=1539001707.001946 sender=:1.3 -> destination=:1.217 serial=178 reply_serial=2
```

**Comment by raveit65** [comment]
Ok, got it :)

**Comment by rbuj** [comment]
Same result on Ubuntu. I couldn't trigger the warning :pensive:
/etc/polkit-1/localauthority/50-local.d/com.ubuntu.disable-suspend.pkla
<pre>[Disable suspend (upower)]
Identity=unix-user:*
Action=org.freedesktop.upower.suspend
ResultActive=no
ResultInactive=no
ResultAny=no

[Disable suspend (logind)]
Identity=unix-user:*
Action=org.freedesktop.login1.suspend
ResultActive=no
ResultInactive=no
ResultAny=no

[Disable suspend when others are logged in (logind)]
Identity=unix-user:*
Action=org.freedesktop.login1.suspend-multiple-sessions
ResultActive=no
ResultInactive=no
ResultAny=no</pre>
After rebooting, the suspend and hibernate options are not shown either in mate-power-preferences, or in Shut Down dialog (System -> Shut Down...).

From command line:
<pre>$ dbus-send --system --print-reply \
> --dest=org.freedesktop.login1 /org/freedesktop/login1 \
> "org.freedesktop.login1.Manager.Suspend" boolean:true
Error org.freedesktop.DBus.Error.AccessDenied: Permission denied</pre>

Sleep button locks the screen by default if "Do Nothing" option is not selected in mate power preferences (General / When the suspend button is pressed):
<pre>$ VBoxManage controlvm "Ubuntu 18.10" acpisleepbutton</pre>

**Comment by raveit65** [comment]
@rbuj 
You should receive another invitation to https://github.com/orgs/mate-desktop/teams/documentation-team/
This group will have read access for mate-user-guide for the moment, because of the other new guys.
But you as collaborator should have write access.
I hope this works.

**Comment by raveit65** [comment]
Those warning are for consolekit, not for logind which is part of systemd.

**Comment by rbuj** [comment]
> Those warning are for consolekit, not for logind which is part of systemd.

I understand. I couldn't get these warnings because I'm using systemd :sweat_smile:
<pre>$ dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" \
/org/freedesktop/ConsoleKit/Manager \
org.freedesktop.ConsoleKit.Manager.Suspend  boolean:true</pre>
@raveit65 excuse me for the inconvenience.

**Comment by rbuj** [comment]
> @rbuj
> You should receive another invitation to https://github.com/orgs/mate-desktop/teams/documentation-team/
> This group will have read access for mate-user-guide for the moment, because of the other new guys.
> But you as collaborator should have write access.
> I hope this works.

I accepted the invitation.

**Comment by raveit65** [comment]
@lukefromdc 
English expression are fine now?

**Comment by lukefromdc** [comment]
Personally I'm not worried about it, I was more concerned with whether you all think it might confuse a new user. I'm not blocking this.

**Comment by raveit65** [comment]
@lukefromdc 
Looks like it is solved or not?
https://github.com/mate-desktop/mate-power-manager/pull/263/commits/5aa6839d0908919668864c0dd9046556ce3e1f8b#diff-549537f424da6b260013ff0d4562e846L266

**Comment by lukefromdc** [comment]
That is fine by me "suspend failure"

**Pull request merged**
