### PR TITLE
Add support for gaming inputs

### PR DESCRIPTION
**Pull request by Zenkibou**
Add support for gaming inputs as well as their icons.
In addition, display the device name even if the vendor is empty.
I tested this with my DualShock 3 connected over bluetooth.

Here is how it looks with this change:
Screenshot at 2022-02-17 09-31-23
Screenshot at 2022-02-17 09-34-46

And how it looks without the change:
Screenshot at 2022-02-17 09-37-23
Screenshot at 2022-02-17 09-39-49

### CODE REVIEW

**Review by rbuj — APPROVED** [review]
It looks good to me, but you don't need to update the translations (mate-power-manager.pot and po/*.po files) since it's performed in several stages.

**Comment by Zenkibou** [comment]
> It looks good to me, but you don't need to update the translations (mate-power-manager.pot and po/*.po files) since it's performed in several stages.

Sorry, I didn't see those change when I committed.
I can update my pull request without those changes if it's better.

**Comment by Zenkibou** [comment]
I made [gaming-input](/Zenkibou/mate-power-manager/tree/gaming-input) branch that doesn't contain the po file changes.

**Comment by Zenkibou** [comment]
See my [gaming-input](/Zenkibou/mate-power-manager/tree/gaming-input) branch without the po changes.

**Comment by raveit65** [comment]
> See my [gaming-input](https://github.com/Zenkibou/mate-power-manager/tree/gaming-input) branch without the po changes.

Looks good, but this needs to be revert here before merging. Your master branch is used here.

**Comment by lukefromdc** [comment]
Cannot test this, I don't have the hardware

**Comment by Zenkibou** [comment]
I wasn't able to change master without closing this pull request, so see the clean pull request #376 without the .po changes.

**Pull request closed without merging**
