### PR TITLE
[ci] Enable Clang Static Analyzer

### PR DESCRIPTION
**Pull request by yetist**
Clang analyzer and `./configure --without-keyring` on debian.

### CODE REVIEW

**Comment by sc0w** [comment]
in this PR `./configure --without-keyring` is running over `clang analyzer`, I think the build must fail if you remove `libgnome-keyring-dev` in debian packages

I noticed this line, it is related?, I don't know if it is possible to change it since the repos:

https://github.com/mate-desktop/mate-dev-scripts/blob/master/travis/docker-build#L847

**Comment by sc0w** [comment]
I think you can just enable clang analyzer here and other jobs can be done in other PRs

**Comment by monsta** [comment]
Hmm... is `--without-keyring` used only for `scan-build` here?

**Comment by monsta** [comment]
All checks passed, so I guess it's good to go?

Do you guys prefer Clang analyzer only on master branch? If yes, then not all the commits can be picked for 1.22 branch.

**Comment by sc0w** [comment]
@monsta do you mean the PR https://github.com/mate-desktop/mate-power-manager/pull/283 ? (1.20 branch)

It haven't clang analyzer

and if we like, I think https://github.com/mate-desktop/mate-power-manager/pull/283 can be picked / adapted for 1.22

**Comment by raveit65** [comment]
Why?
Please do not use Clang analyzer on stable branches! 
We don't do that in other packages.

**Comment by raveit65** [comment]
You can fix issue of clang and ccpcheck on master.

**Comment by monsta** [comment]
I'm fine with that. #283 looks like it can be adapted, yes.

**Comment by sc0w** [comment]
@raveit65 

> Please do not use Clang analyzer on stable branches!

I don't understand you, you are wrong, I didn't say that, I didn't do that

**Comment by sc0w** [comment]
@monsta done with https://github.com/mate-desktop/mate-power-manager/pull/286

**Pull request merged**
