### PR TITLE
When coming back from idle mode, restore previous brightness instead of ...

### PR DESCRIPTION
**Pull request by SukkoPera**
...using default.

### CODE REVIEW

**Comment by NiceandGently** [comment]
@monsta 
@stefano-k 
Can you please review this PR, this will close several reports

**Comment by monsta** [comment]
But it's stated above that this PR has bugs. Shouldn't the author correct it first?

**Comment by NiceandGently** [comment]
ok,
@SukkoPera 
Can you fix that?

**Comment by SukkoPera** [comment]
Sure I can, but I need some time. How urgent is this? It's pretty obvious anyway, anyone could do it :).

**Comment by monsta** [comment]
It's not urgent I think, it's not a fix for some crash or freeze or something like that, after all :)

**Comment by flexiondotorg** [comment]
@SukkoPera If you have the time please do submit a revised pull-request. Thanks :-)

**Comment by snugglej** [comment]
Sorry to not really add anything beneficial to this, but was this ever pushed upstream? I'm really struggling with a Dell XPS 13 which has a bug with light management and I think this may fix it.

**Comment by raveit65** [comment]
@SukkoPera 
any NEWS ?
or should we close this?

**Comment by dotnetCarpenter** [comment]
I'm not a C developer but this PR looks extremely small. Wouldn't it be quicker if one of the members here spend half an hour pulling the branch, save the original brightness value, call `gpm_kbd_backlight_set (backlight, value);`  and merged it into master, than talking about it here?

You'll get fanfare if you do it!

**Comment by raveit65** [comment]
Closing because author of PR didn't answer on questions since a long time.

**Pull request closed without merging**
